- src/commands/inspect.ts
- src/commands/install.ts
- src/commands/installed.ts
- src/commands/uninstall.ts
- src/commands/view.ts
- src/constants.ts
- src/index.ts
- src/utils/config-manager.ts
- src/utils/registry-utils.ts
- src/utils/server-actions.ts
- src/utils/server-manager.ts
This PR adds support for cline through --client flag.
Users can now manage servers for cline by adding '--client cline' to existing commands. If no client is specified, we default to 'claude' with the following message to user: "Client not provided, defaulting to claude"
Might add better ways to manage servers across clients in the future, for example, to allow user to select from identified clients from options if none specified. Additionally, might need to think of a better user flow when using the inspect, view commands (since they aren't too client dependent).
> Add support for 'cline' client

- README.md
- build.mjs
- package-lock.json
- package.json
- src/commands/run.ts
- src/constants.ts
- src/index.ts
- src/services/gateway-server.ts
- src/types/registry.ts
- src/utils/config-manager.ts
- src/utils/mcp-handlers.ts
- src/utils/registry-utils.ts
- src/utils/runtime-utils.ts
- src/utils/server-manager.ts
- tsconfig.json
PR makes the following changes:
1. install command: sets new client configuration:
**old:**
```json
"smithery-fetch": {
"command": "npx",
"args": [
"-y",
"@smithery-fetch"
]
},
```
**new:**
```json
"smithery-fetch": {
"command": "npx",
"args": [
"-y",
"@smithery/cli",
"run",
"smithery-fetch",
"--config",
"{}"
]
}
```
2. When client executes run command, following happens:
- calls registry to get server details (e.g., available connections)
- if multiple connections, prioritises SSE connections
**- for SSE connection:**
1. uses config values to create SSE connection url
2. creates a client to communicate with remote SSE server
3. creates proxy STDIO server as gateway to communicate with remote server with client as passthrough
**- for STDIO connection:**
1. uses config to POST request and …
> Add 'run' command

- src/commands/install.ts
- src/commands/run.ts
- src/services/gateway-server.ts
- src/utils/smithery-settings.ts
- create smithery settings.json to hold userId and server cache in future
- send userId on POST request during STDIO server runs, if consented (prompted during initial installation of any server)
- inform user of remote SSE server installation
> Add analytics and inform user of remote server installation

- src/commands/run.ts
- src/services/smithery-runner.ts
- src/services/sse-runner.ts
- use a more robust SSE connection pattern by using eventsource to talk to SSE server directly instead of previous proxy client/server pattern
- update name from gateway server to smithery runner
- move towards new organisation of separate runners for sse and stdio (currently in a slightly awkward state, will add CreateSTDIORunner into a separate function in upcoming PR)
> Fix reconnection issue

- src/test/config-manager.test.ts
- src/utils/config-manager.ts
- Fix for https://github.com/smithery-ai/cli/issues/21
- Also adds tests for config manager
> Preserve existing keys in client configurations

- src/run/ws-runner.ts
PR adds logging for successful websocket connection so it doesn't seem to be struck connecting
> Log websocket connection success

- src/run/proxy-transport.ts
- src/run/ws-runner.ts
- proxy transport with underlying websocket transport that's closed after an idle timeout
- buffer for messages till underlying transport is reconnected after timeout
> Add lazy connection through proxy transport

- build.mjs
Fixes installation issues on Linux where paths were incorrectly resolving to /home/runner (https://github.com/smithery-ai/cli/issues/37)
> Fix (linux): Prevent hardcoding of user environment variables during build

- README.md
- package-lock.json
- package.json
- src/index.ts
- src/install.ts
- Update README to document new `--data` flag for server installation
- Modify `index.ts` and `install.ts` to support passing configuration data directly
- Allow skipping interactive prompts by providing configuration as JSON
- Improve installation process to use pre-provided config values when available
> feat: Add support for pre-configured server installation data

- src/types/registry.ts
- src/utils.ts
- Use server's remote flag to identify which connection to choose
- When remote is false, prioritise local connection
- Fallback to first available connection when all conditions fail
> Use remote flag to choose server connection

- README.md
- src/index.ts
PR allows use of config flag instead of data flag to let users pass JSON configuration during installation
> Use config flag instead of data

- src/utils/runtime.ts
```where npx``` in windows returns both ```\npx``` and ```npx.cmd``` path. Use only path that contains .cmd extension
> Only use .cmd path for npx

- src/install.ts
- src/run/stdio-runner.ts
- workaround until SDK is fixed to allow running servers in windows without additional ```cmd /c``` args
- https://github.com/modelcontextprotocol/typescript-sdk/issues/101
- https://github.com/smithery-ai/mcp-obsidian/issues/19
> Fix: run npx in windows through cmd /c

- src/commands/install.ts
- src/utils/config.ts
- Remove organisation scope from server's key in client config JSON
- Issue: https://github.com/smithery-ai/typescript-sdk/issues/63#issuecomment-2729376192
> Update server normalisation to prevent cursor tool call issue

- CHANGELOG.md
- package.json
- src/client-config.ts
- src/commands/list.ts
- src/commands/uninstall.ts
- src/constants.ts
- src/test/config-manager.test.ts
I tried to keep the change somewhat minimal. Switched from a `string` config to a type that points either to a config or a command. Reading a "command" config will return no servers right now, since VS Code doesn't support that. I validated that you can successfully install them on macOS and Windows and that existing install configs work.
Refs https://github.com/smithery-ai/cli/issues/76
> feat: support installing servers to vscode

- CHANGELOG.md
- package.json
- src/index.ts
Fixed config parsing on Windows command prompt where single quotes were being passed literally instead of being interpreted
> fix: windows cmd json parsing error

- CHANGELOG.md
- package.json
- src/commands/run/index.ts
- src/utils/config.ts
- Modified runtime config validation to allow empty strings for required fields
- Added separate config validation for run vs install commands
- Improved error handling for missing required fields during runtime
> feat(run): allow empty strings for required config fields during runtime

- package.json
This PR adds the [`repository` field](https://docs.npmjs.com/cli/v11/configuring-npm/package-json#repository) to `package.json`.
Since the docs recommend running this with `npx`, I wanted to look at the source code. A common pattern I use is `npm repo <package-name`. However, this didn't work with `@smithery-ai/cli`:
```shell
> npm repo @smithery/cli
npm error no repository
```
Adding this key will make it easier for users to validate the source code for the CLI tool.
> chore: add repo link to package.json

- src/client-config.ts
- src/constants.ts
[Amazon Bedrock Client for Mac](https://github.com/aws-samples/amazon-bedrock-client-for-mac) provides an mcp client for use with Amazon Bedrock models in MacOS environment. Below is a test run.
install @mcp-examples/weather
mcp settings applied
client uses tool
> add support for amazon-bedrock

- src/client-config.ts
- src/constants.ts
As described in this [AWS MCP blog](https://aws.amazon.com/blogs/devops/extend-the-amazon-q-developer-cli-with-mcp/#:~:text=the%20database%20schema.-,configuring,-Model%20Context%20Protocol) post, this PR should add support for Amazon Q.
Amazon Q using smithery installed MCP servers:
> add amazonq client

- package.json
- src/commands/dev.ts
- src/commands/inspect.ts
- src/commands/playground.ts
- src/index.ts
- src/lib/browser.ts
- src/lib/dev-lifecycle.ts
- src/lib/tunnel.ts
- src/logger.ts
- Reduced noisy logs and made them debug logs (tunnel started/stopped etc.)
- User can run `npx @smithery/cli dev --debug` to enable debug logs
- User can run `npx @smithery/cli dev --prompt "say hello"` to set the initial playground message (URL query param `prompt`)
- Added a "one-click deploy: https://smithery.ai/new" log
Final output:
> devex around playground
