smithery-ai/cli

- src/index.ts
- src/utils/server-manager.ts
PR allows JSON config to be encoded when saving to client configurations, and decode during run command maintaining backward compatibility with non-encoded configs.
> Escape JSON config

- src/services/stdio-runner.ts
Users on Windows were encountering errors when executing commands with spaces in paths, resulting in errors like:
`'C:\Program' is not recognized as an internal or external command`
- Added Windows-specific path handling in the STDIO runner that:
1. Resolves full command paths using the `where` command when needed
2. Handles spaces in paths by using Node's executable (process.execPath) as a wrapper
3. Maintains fallback behavior if path resolution fails
> Fix: handle Windows paths with spaces in STDIO runner

- src/services/stdio-runner.ts
- src/utils/config-manager.ts
reference: https://github.com/smithery-ai/typescript-sdk/issues/36 
To be updated to 'windsurf' directory after transition phase from windsurf-next
> Fix windsurf next path

- jest.config.js
- package-lock.json
- package.json
- src/test/smithery-settings.test.ts
- src/utils/smithery-settings.ts
- Prompts for custom path if default path resolves to write error (allows skip)
- Adds custom path for smithery config to env and reads from env if present
- Adds tests for smithery settings
> Allow custom path for smithery config on write error to default path

- src/services/stdio-runner.ts
adds fetch import in STDIO runner
> Fix fetch not defined in STDIO runner

- src/constants.ts
- src/utils/config-manager.ts
Hi. I am working on the integration of MCP and Smithery into Witsy (https://github.com/nbonamy/witsy).
This is a WIP but you can see the state of integration here: https://github.com/nbonamy/witsy/issues/80#issuecomment-2672157708
Would love to see this merged: without this would be very hard for Witsy users to add Smithery.ai MCP servers.
Thanks!
> https://github.com/nbonamy/witsy integration

- package-lock.json
- package.json
- src/index.ts
- src/install.ts
- src/registry.ts
- src/run/index.ts
- src/run/stdio-runner.ts
- src/run/ws-runner.ts
- src/smithery-config.ts
- src/utils.ts
- PR refactors the run command. Services, commands, utils folder would be eventually deprecated.
- Also improves the handling of smithery settings config
> REFACTOR: run command

- src/client-config.ts
- src/constants.ts
- src/utils/config-manager.ts
Hi. I am the developer of [enconvo.com](http://enconvo.com/), which is an AI Launcher for MacOS, and I recently added MCP support.
Smithery is a great platform, and I want my users to use Smithery easily with Enconvo.
Would love to see this merged.
Thanks!
> Add new client: enconvo

- src/install.ts
- src/test/install.test.ts
- adds error catching around analytics consent, to let installation be unaffected on failure
- adds error catching around server installation
- updates install test file
> Update install test, and improve error handling during installation

- README.md
- package.json
- src/client-config.ts
- src/constants.ts
- src/index.ts
- src/inspect.ts
- src/install.ts
- src/registry.ts
- src/run/index.ts
- src/run/stdio-runner.ts
- src/smithery-config.ts
- src/test/install.test.ts
- src/uninstall.ts
- src/utils.ts
- src/utils/config-manager.ts
- creates new inspect command
- creates new uninstall command
- formatting
- updates README
> Refactor: inspect, uninstall commands

- README.md
- package.json
- src/client-config.ts
- src/index.ts
- src/install.ts
- src/logger.ts
- src/registry.ts
- src/smithery-config.ts
- src/test/install.test.ts
Adds ```--verbose``` mode to show detailed logs of what's happening behind the scenes
> Add --verbose flag

- src/install.ts
- src/test/install.test.ts
- src/utils.ts
- utilities to check and prompt for UV installation when required
- updates install tests
> Prompt for UV installation

- README.md
- src/index.ts
- src/list.ts
PR adds list command to list available client:
```bash
smithery/cli list clients
```
> Add list command

- src/run/stdio-runner.ts
- src/utils.ts
- find and add bun, uv paths to env
- create dedicated function for runtime environment handling
> Enhance runtime environment

- src/run/stdio-runner.ts
- src/utils/runtime.ts
- simplifies setting up of PATH in runtime environment (https://github.com/smithery-ai/cli/issues/50)
- logs runtime environment for better debugging
> Simplify runtime environment PATH

- .github/workflows/publish-beta.yml
- src/inspect.ts
- add GitHub workflow for beta release
- minor enhancement to inspect command by adding runtime environment to transport creation
> Add workflow for beta release

- src/utils/runtime.ts
Search from env PATH first before the other resolution methods
> Enhance npx resolution

- CHANGELOG.md
- build.mjs
- package.json
- src/client-config.ts
- src/commands/inspect.ts
- src/commands/install.ts
- src/commands/list.ts
- src/commands/run/proxy-transport.ts
- src/commands/run/stdio-runner.ts
- src/commands/run/ws-runner.ts
- src/constants.ts
- src/index.ts
- src/test/install.test.ts
- src/test/registry.test.ts
- src/test/smithery-settings.test.ts
- src/test/ws-runner.test.ts
- src/utils/config.ts
- src/utils/runtime.ts
latest version of cursor (0.47.x) supports MCP installation through global config at `~/.cursor/mcp.json`
> Add cursor support

- CHANGELOG.md
- src/commands/install.ts
- src/commands/run/index.ts
- src/index.ts
- src/registry.ts
- src/test/server-config.test.ts
- src/utils/config.ts
- implements --key flag to fetch saved config using smithery api key (preparatory, not functional yet)
- improve config validation and collection during server installation
> Add support for fetching saved config using --key flag

- CHANGELOG.md
- package.json
- src/commands/install.ts
- src/commands/run/index.ts
- src/index.ts
- src/registry.ts
- src/test/server-config.test.ts
- src/utils/config.ts
- src/utils/runtime.ts
- Refactored the install command for better code organization and maintainability
- Enhanced API key handling to improve backward compatibility and isolate functions when API key is provided
- Optimized registry to reduce database calls by returning both server details and saved configuration in a single request
> Improve saved config fetch, backward compatibility, refactors

- CHANGELOG.md
- package.json
- src/commands/inspect.ts
- src/commands/run/ws-runner.ts
- Enhanced WebSocket error handling with specific handlers for connection errors (code -32000) and protocol errors (codes -32602, -32600)
- Added automatic reconnection attempt for server-initiated connection closures
> Enhance websockets error handling

- CHANGELOG.md
- src/commands/run/ws-runner.ts
linked to https://github.com/21st-dev/magic-mcp/issues/8
> Silence non-critical MCP errors to improve UX

- CHANGELOG.md
- package-lock.json
- package.json
- src/commands/run/index.ts
- src/commands/run/proxy-transport.ts
- src/commands/run/ws-runner.ts
Ref: https://github.com/smithery-ai/typescript-sdk/pull/144
> Pass optional api key to ws gateway

- CHANGELOG.md
- package-lock.json
- package.json
Updated @modelcontextprotocol/sdk to v1.8.0 which fixes Windows spawn issues ([modelcontextprotocol/typescript-sdk#101](https://github.com/modelcontextprotocol/typescript-sdk/issues/101), [modelcontextprotocol/typescript-sdk#198](https://github.com/modelcontextprotocol/typescript-sdk/pull/198))
> Update mcp sdk to fix windows spawn issues using cross spawn

- CHANGELOG.md
- package.json
- src/commands/run/stdio-runner.ts
- Enhanced cleanup process in stdio-runner with better handling of client disconnections and process termination
- Added safety timeout for transport cleanup operations to ensure process termination
> fix: Improve stdio-runner cleanup process

- CHANGELOG.md
- package.json
- src/commands/run/proxy-transport.ts
- src/commands/run/ws-runner.ts
- Enhanced WebSocket runner cleanup process with improved handling of connection termination
- Added safety timeout for WebSocket transport cleanup operations
- Added better state management for clean vs unexpected shutdowns in WebSocket connections
> fix: Improve ws-runner cleanup process

- CHANGELOG.md
- package.json
- src/commands/run/ws-runner.ts
- Added random jitter (0-1000ms) to WebSocket reconnection backoff
- Refactored WebSocket runner and improved console logs
> feat: add jitter to WebSocket reconnection logic and refactor WS runner

- CHANGELOG.md
- src/commands/run/index.ts
- src/commands/run/stdio-runner.ts
- src/utils/analytics.ts
- Reduces spam
- Resolves SMI-219
> Use API key for calling track

- CHANGELOG.md
- package.json
- src/commands/run/runner-utils.ts
- src/commands/run/ws-runner.ts
- Added WebSocket heartbeat mechanism that pings every 30 seconds to maintain connection
- Added 15-minute idle timeout with automatic connection shutdown
> feat: add heartbeat to WS connection

- CHANGELOG.md
- package.json
- src/commands/run/stdio-runner.ts
- src/commands/run/ws-runner.ts
- Enhanced stdio and WS runners with more gracious error handling
- Improved logging in stdio runner with timestamps
> fix: improve stdio error handling

- CHANGELOG.md
- package.json
- src/client-config.ts
- src/constants.ts
Renamed roo-code to roocode for consistency
> refactor: rename roo-code to roocode

- CHANGELOG.md
- package.json
- src/commands/run/index.ts
- src/commands/run/stdio-runner.ts
- src/test/install.test.ts
- src/test/server-config.test.ts
- src/utils/config.ts
- Refactored config handling to treat empty strings ("") as undefined values
- Added stricter validation for required fields in configuration
- Improved process exit handling with proper exit code 0 on transport close
- Removed redundant config validation in and index.ts
- Streamlined config validation flow in config.ts
> refactor: improve config validation, process clean up

- src/client-config.ts
- src/constants.ts
Hi. I'm the developer of BoltAI.com, a native AI chat client for Mac. I've added support for MCP recently and would love to integrate with smithery.
Thank you
https://github.com/user-attachments/assets/2d03b29b-b1a9-4ce8-97e3-00a70f88a81d
> Add new client: BoltAI

- CHANGELOG.md
- package.json
- src/commands/run/index.ts
- src/commands/run/streamable-http-runner.ts
- src/constants.ts
Added session termination on transport close for Streamable HTTP runner
> feat: session termination

- build.mjs
- package-lock.json
- package.json
- src/commands/dev.ts
- src/commands/playground.ts
- src/index.ts
- src/smithery-config.ts
- src/utils/runtime.ts
- Add `playground` command
- Save API keys in home directory
> Playground command

- .github/ISSUE_TEMPLATE/1-bug-report.yaml
- .github/ISSUE_TEMPLATE/2-feature-proposal.yaml
- .github/pull_request_template.md
1. issue templates for feature and bugs 
2. pr template 
to help the team manage pull request and PRs
> feat: pr and issue template

- src/commands/run/stdio-runner.ts
- src/commands/run/streamable-http-runner.ts
PR adds process exit after cleanup to prevent hanging processes.
> always call process exit after cleanup

- package.json
- src/lib/browser.ts
- Add `dev` query parameter to playground link so playground can show dev specific ui
> feat: add dev query param to playground link
